# Generated by Django 4.1.5 on 2023-02-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Дом', 'Дом'), ('Квартира', 'Квартира'), ('Новостройка', 'Новостройка')], default='Дом', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('rooms', models.CharField(choices=[('1', '2'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=50)),
                ('floor', models.CharField(choices=[('1', '2'), ('2', '2'), ('3', '3'), ('4', '4')], default='3', max_length=50)),
                ('category', models.ManyToManyField(to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('rooms', models.CharField(choices=[('1', '2'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=50)),
                ('category', models.ManyToManyField(to='products.category')),
            ],
        ),
    ]
