# Generated by Django 4.1.5 on 2023-02-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Первомайский', 'Первомайский'), ('Октябрьский', 'Октябрьский'), ('Свердловский', 'Свердловский'), ('Ленинский', 'Ленинский ')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Студия', 'Студия'), ('Однокомнатная', 'Однокомнатная'), ('Двухкомнатная', 'Двухкомнатная'), ('Трехкомнатная', 'Трехкомнатная'), ('Четырехкомнатная', 'Четырехкомнатная'), ('Пятикомнатная', 'Пятикомнатная'), ('Шестикомнатная', 'Шестикомнатная')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Дом', 'Дом'), ('Квартира', 'Квартира'), ('Новостройка', 'Новостройка')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('square', models.IntegerField()),
                ('living_square', models.IntegerField()),
                ('ceiling_height', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('repair', models.CharField(max_length=100)),
                ('furniture', models.CharField(max_length=100)),
                ('bathroom', models.CharField(max_length=100)),
                ('window', models.CharField(max_length=100)),
                ('warp_floor', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10)),
                ('balcony', models.CharField(choices=[('Балкон', 'Балкон'), ('Лоджия', 'Лоджия')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.area')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.rooms')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.type')),
            ],
        ),
    ]
