# Generated by Django 4.1.5 on 2023-02-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apps',
            new_name='Apartment',
        ),
    ]
