# Generated by Django 4.1.4 on 2023-03-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
