# Generated by Django 4.1.5 on 2023-02-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='warp_floor',
            new_name='warm_floor',
        ),
    ]
