# Generated by Django 4.1.5 on 2023-02-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_apps_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='house',
            name='title',
        ),
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='category',
            field=models.ManyToManyField(default='Квартира', to='products.category'),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.ManyToManyField(default='Дом', to='products.category'),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=50),
        ),
    ]
