# Generated by Django 4.1.5 on 2023-02-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_warp_floor_product_warm_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='living_square',
            new_name='living_space',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='square',
            new_name='space',
        ),
    ]
