# Generated by Django 4.1.5 on 2023-02-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_living_square_product_living_space_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='space',
            new_name='square',
        ),
    ]
