# Generated by Django 4.1.5 on 2023-02-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_space_product_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ceiling_height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='living_space',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='square',
            field=models.FloatField(),
        ),
    ]
